Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Configuração básica da VM
  config.vm.hostname = "devops-vm"
  config.vm.network "private_network", ip: "192.168.56.10"
# Expondo backend FastAPI
  config.vm.network "forwarded_port", guest: 30000, host: 30000

  # Expondo frontend (Nginx ou HTML+JS)
  config.vm.network "forwarded_port", guest: 30001, host: 30001
  # Provisionamento usando Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisionamento.yml"
  end

  # Ajuste de recursos
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
end

